const B = "http://127.0.0.1:3106";
const post = (p, b) => fetch(B + p, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(b ?? {}) }).then(async (r) => ({ ok: r.ok, body: await r.json().catch(() => ({})) }));
import WebSocket from "ws";
await post("/api/workspace/open", { path: "/tmp" });
const ws = new WebSocket("ws://127.0.0.1:3106/api/opencode/terminal");
const seen = [];
ws.on("message", (d) => { seen.push(d.toString()); console.log("WSMSG len", d.length); });
await new Promise((r, j) => { ws.on("open", r); ws.on("error", j); });
console.log("ws open, starting TUI");
console.log(JSON.stringify(await post("/api/opencode/start", { cols: 120, rows: 30 })));
await new Promise((r) => setTimeout(r, 2500));
console.log("after 2.5s, msgs:", seen.length);
console.log("sending OSC 11 reply (what xterm.js auto-sends)...");
ws.send(JSON.stringify({ type: "input", data: "\x1b]11;rgb:0000/0000/0000\x1b\\" }));
await new Promise((r) => setTimeout(r, 2500));
console.log("after reply, msgs:", seen.length, seen.length > 1 ? "PASS bidirectional mirror" : " 대선 no follow-up (check)");
for (const [i, m] of seen.slice(0, 4).entries()) console.log(i, JSON.stringify(m.slice(0, 160)));
ws.close();
await post("/api/opencode/stop", {});
process.exit(0);
